### ISSUE TITLE
Work based on your plugin

### ISSUE THREAD

**Issue by BenediktBurger** [Attolab/pymodaq_plugins_pylablib_camera#4]
I have a new plugins repository (https://github.com/BenediktBurger/pymodaq_plugins_basler) based on your work, thanks for your work.

It uses, however, the manufacturer's driver instead of the pylablib version, which did not comply at time of writing with the pylablib standards... (https://github.com/AlexShkarin/pyLabLib/issues/54)

**Comment by rgeneaux** [comment]
Great, glad you could make it work. Some colleague have some Basler cameras, I'll ask them to try out your plugin.

Do you want to release your plugin on pypi, so that it becomes visible to evyerone?

**Comment by BenediktBurger** [comment]
> Do you want to release your plugin on pypi, so that it becomes visible to everyone?

That's my plan, see
- https://github.com/BenediktBurger/pymodaq_plugins_basler/issues/3

**Comment by BenediktBurger** [comment]
Would you mind informing me, when you release your plugin on pypi?
Then I can add you as my dependency instead of copying a file from your repo.

Thanks.

**Comment by rgeneaux** [comment]
Plugin is published on pypi
