### ISSUE TITLE
Make a PyPI release

### ISSUE THREAD

**Issue by BenediktBurger** [Attolab/pymodaq_plugins_pylablib_camera#8]
A PyPI release woud be great to base my work on your code.

**Comment by BenediktBurger** [comment]
Thanks.

**Comment by rgeneaux** [comment]
Released https://pypi.org/project/pymodaq-plugins-pylablib-camera/

Note that I also renamed the package to pymodaq_plugins_pylablib_camera and transferred ownership of the repository to my institution (changes the URL)
